version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "80:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-django-insecure-fallback-key}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    volumes:
      - ./data:/app/data
    restart: unless-stopped