version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-django-insecure-fallback-key}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped