version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped