# Generated by Django 5.2.6 on 2025-09-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='테이블 번호')),
                ('seats', models.IntegerField(default=4, verbose_name='좌석 수')),
                ('status', models.CharField(choices=[('empty', '빈 테이블'), ('ordered', '주문 완료'), ('cooking', '조리 완료'), ('paid', '결제 완료')], default='empty', max_length=10, verbose_name='상태')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '테이블',
                'verbose_name_plural': '테이블',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='그룹명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('tables', models.ManyToManyField(to='tables.table', verbose_name='테이블들')),
            ],
            options={
                'verbose_name': '테이블 그룹',
                'verbose_name_plural': '테이블 그룹',
            },
        ),
    ]
