# Generated by Django 5.2.6 on 2025-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('empty', '빈 테이블'), ('ordered', '주문 완료'), ('cooking', '조리 중'), ('ready', '조리 완료'), ('paid', '결제 완료')], default='empty', max_length=10, verbose_name='상태'),
        ),
    ]
