# Generated by Django 5.2.6 on 2025-09-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('options', models.JSONField(default=list, help_text='예: ["고추빼고", "면 많이"]', verbose_name='옵션')),
                ('min_order', models.IntegerField(default=1, verbose_name='최소 주문 수량')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='옵션명')),
                ('price', models.IntegerField(default=0, verbose_name='추가 가격')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_options', to='menus.menu', verbose_name='메뉴')),
            ],
            options={
                'verbose_name': '메뉴 옵션',
                'verbose_name_plural': '메뉴 옵션',
            },
        ),
    ]
