# Generated by Django 5.2.6 on 2025-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='requires_cooking',
            field=models.BooleanField(default=True, verbose_name='주방 조리 필요'),
        ),
    ]
