# Generated by Django 5.2.6 on 2025-09-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '주문 대기'), ('confirmed', '주문 확인'), ('cooking', '조리 중'), ('ready', '조리 완료'), ('served', '서빙 완료'), ('paid', '결제 완료')], default='pending', max_length=10, verbose_name='상태')),
                ('total_amount', models.IntegerField(default=0, verbose_name='총 금액')),
                ('discount', models.IntegerField(default=0, verbose_name='할인 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='테이블')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('options', models.JSONField(default=list, help_text='선택된 옵션 목록', verbose_name='옵션')),
                ('unit_price', models.IntegerField(verbose_name='단가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='메뉴')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='주문')),
            ],
            options={
                'verbose_name': '주문 상세',
                'verbose_name_plural': '주문 상세',
            },
        ),
    ]
