# Generated by Django 5.2.6 on 2025-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('cooking', '조리 중'), ('ready', '조리 완료')], default='cooking', max_length=20, verbose_name='조리 상태'),
        ),
    ]
