# Generated by Django 5.2.6 on 2025-11-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_status'),
        ('tables', '0002_alter_table_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='할인명')),
                ('discount_type', models.CharField(choices=[('amount', '정액 할인'), ('percent', '정률 할인')], max_length=10, verbose_name='할인 유형')),
                ('value', models.IntegerField(verbose_name='할인값')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '할인',
                'verbose_name_plural': '할인',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='결제 방식명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '결제 방식',
                'verbose_name_plural': '결제 방식',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '주문 대기'), ('ordered', '주문 완료'), ('confirmed', '주문 확인'), ('cooking', '조리 중'), ('ready', '조리 완료'), ('served', '서빙 완료'), ('paid', '결제 완료')], default='pending', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.table', verbose_name='테이블'),
        ),
    ]
